---
spring:
  profiles: subject
  application:
    name: subject
words: Yogesh,Gundu,Boss,Don,Awesome

---
spring:
  profiles: article
  application:
    name: article
words: a,the

---
spring:
  profiles: adjective
  application:
    name: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profiles: verb
  application:
    name: verb
words: ran,knew,had,saw,bought
